StorageBodySize=100
StorageMotorSize=100
StorageAccessorySize=100
StorageAutoSize=100

AccessorySuppliers=3
MotorSuppliers=3
BodySuppliers=3

Workers=5
Dealers=1

BodySupplierDelay=1200
MotorSupplierDelay=1100
AccessorySupplierDelay=800
DealerDelay=1400

LogSale=true
